### ISSUE TITLE
issue/#09   DB作成：init.sql追加

### ISSUE THREAD

**Issue by RongRongRabbit** [WenchaY/trad-crafts-platform#18]
### 作業背景
システムを設計するためにDBを作成する必要がある

### 作業項目

- [x] init.sql

### 作業結果
<img width="1169" alt="craft_characteristic" src="https://github.com/WenchaY/trad-crafts-platform/assets/143078851/5199b2a0-6ccb-41f3-a1a1-9cac49964084">
<img width="882" alt="craft_location" src="https://github.com/WenchaY/trad-crafts-platform/assets/143078851/877036e5-0d9d-497b-8e8a-55266c3b34f2">
<img width="978" alt="users" src="https://github.com/WenchaY/trad-crafts-platform/assets/143078851/d5daf605-0eee-4f32-baed-7740386f650c">

**Comment by WenchaY** [comment]
### comment
- https://github.com/WenchaY/trad-crafts-platform/pull/19 にReviewを記入しました
- なるべく`created_at`、`updated_at`と`is_deleted`を追加したいです
- テーブルの設計をもうちょっと考えてほしいです
  - 具体的は[データベースオブジェクトの命名規約](https://qiita.com/genzouw/items/35022fa96c120e67c637)を参考に
  - [【MySQL】よく使うデータ型をまとめて紹介（テーブル設計）](https://marunaka-blog.com/mysql-data-type/3608/)
  - [RDBのデータモデリング・テーブル設計の際に参考にしている考え方と資料](https://zenn.dev/rebi/articles/28c7f1fee5730a)

**Comment by RongRongRabbit** [comment]
### reply
- comment１のReview指摘を修正いたしました
- comment２の三つテーブルに`created_at`、`updated_at`と`is_deleted`を追加いたしました
- comment３テーブルの設計については、命名規則を統一させました
